pool:
  vmImage: 'ubuntu-latest'
  
trigger:
- master

strategy:
  matrix:
    cli:
      MODULE: "cli"
    nginx:
      MODULE: "nginx"
    xdebug:
      MODULE: "xdebug"
    mysql:
      MODULE: "mysql"

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'

- script: |
    cd images/
    npm install twig
    ./generate.sh
    ./build.sh ${MODULE}
  displayName: 'Build image and push'

- task: Docker@2
  condition: eq(variables['MODULE'], 'mysql')
  displayName: 'Push MySQL Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-mysql'
    command: 'push'
    tags: |
      55
      56
      57
      8

- task: Docker@2
  condition: eq(variables['MODULE'], 'xdebug')
  displayName: 'Push XDebug Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-nginx'
    command: 'push'
    tags: |
      php72-xdebug
      php71-xdebug

- task: Docker@2
  condition: eq(variables['MODULE'], 'nginx')
  displayName: 'Push Nginx Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-nginx'
    command: 'push'
    tags: |
      php71
      php72
      php73

- task: Docker@2
  condition: eq(variables['MODULE'], 'cli')
  displayName: 'Push Cli Images'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'shyim/shopware-cli'
    command: 'push'
    tags: |
      php71
      php72
      php73
