#!/usr/bin/env bash

FILE="$0"

if [ -L "$0" ]; then
  FILE=$(readlink "$0")
fi

DIR=$(dirname ${FILE})


# Need to be in docker folder for docker-compose
cd ${DIR}

case "$1" in
  up)
    docker-compose up -d
    ;;
  down)
    docker-compose down
    ;;
  shell)
    docker-compose exec -e COLUMNS="`tput cols`" -e LINES="`tput lines`" -e SHELL=bash cli bash
    ;;
  *)
    docker-compose exec cli bash /opt/swdc/swdc-inside "$@"
    ;;
esac
