FROM debian:stretch-slim

ENV SHOPWARE_ENV docker

RUN mkdir -p /usr/share/man/man1/ && \
    apt-get update && \
    apt-get install --no-install-recommends -y curl wget ca-certificates && \
    curl https://packages.sury.org/php/README.txt | bash && \
    apt-get update && apt-get install --no-install-recommends -y \
    openjdk-8-jre-headless \
    ant \
    patch \
    mariadb-client \
    php{{ phpVersion }}-cli \
    php{{ phpVersion }}-xml \
    php{{ phpVersion }}-zip \
    php{{ phpVersion }}-json \
    php{{ phpVersion }}-zip \
    php{{ phpVersion }}-gmp \
    php{{ phpVersion }}-mysql \
    php{{ phpVersion }}-sqlite3 \
    php{{ phpVersion }}-mbstring \
    php{{ phpVersion }}-bcmath \
    php{{ phpVersion }}-gd \
    php{{ phpVersion }}-curl \
    git \
    sudo \
    gpg \
    gpg-agent \
    curl \
    wget \
    nano \
    ssmtp \
    unzip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    cd /opt/ && \
    git clone https://github.com/shopwareLabs/sw-cli-tools.git \
    && cd sw-cli-tools \
    && composer install --no-dev \
    && ln -s /opt/sw-cli-tools/bin/sw /usr/local/bin/sw \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && useradd dev \
    && mkdir /home/dev \
    && chown -R dev: /home/dev \
    && curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash - \
    && apt-get install nodejs -y

ENV HOME /home/dev
USER dev

COPY rootfs/ /

RUN composer global require hirak/prestissimo

WORKDIR /var/www/html
