FROM {% block image_from %}php:{{ phpVersion }}-cli-alpine{% endblock %}

LABEL org.opencontainers.image.source https://github.com/shyim/shopware-docker
ENV XDEBUG_MODE=debug \
    SMTP_ADDRESS=smtp:1025
ENV PS1 '${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u\[\033[01;33m\]@\[\033[01;36m\]\h \[\033[01;33m\]\w \[\033[01;35m\]\$ \[\033[00m\]'
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/
COPY --from=ghcr.io/shyim/shopware-docker/sendmail /sendmail /usr/bin/sendmail
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer-native-1
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer-native-2

ENV PHP_DUMP_SERVER_URL=http://dump-server:9009

RUN set -x && \
      apk add --no-cache \
      nginx \
      shadow \
      gettext \
      unzip \
      bash \
      wget \
      git \
      zip \
      bash-completion \
      patch \
      mariadb-client \
      make && \
    install-php-extensions bcmath gd intl mysqli pdo_mysql sockets bz2 gmp soap zip gmp pcntl posix redis pcov imagick xsl{% if phpVersionNumeric >= 74 %} ffi excimer {% endif %} {% if production %} opcache {% endif %} {% if xdebug %} xdebug{% if phpVersionNumeric >= 71 and xdebug == 2 %}-2.9.8{% endif %} {% endif %} && \
    rm -rf /tmp/* && \
    useradd dev && \
    mkdir /home/dev && \
    mkdir -p /opt/phpstorm-coverage && \
    chown -R dev /home/dev /opt/ && \
    cd /tmp && \
    wget https://github.com/shyim/fnm-alpine/releases/download/1.0.0/fnm && \
    mv fnm /usr/local/bin && \
    chmod +x /usr/local/bin/fnm && \
    apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing flamegraph && \
    apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/v3.13/community gnu-libiconv{% if xdebug %} && \
    {% if xdebug == 2 %}
    echo 'xdebug.remote_enable=1' > /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.remote_autostart=0' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.remote_port=9000' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.remote_log=/tmp/xdebug.log' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.idekey=PHPSTORM' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.profiler_enable=0' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.profiler_enable_trigger=1' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.profiler_output_dir="/tmp/xdebug"' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.profiler_output_name = "cachegrind.out.%R.%t"' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.auto_trace=0' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.trace_enable_trigger=1' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.trace_output_dir="/var/www/html/traces"' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.trace_output_name="trace.%R.%t"' >> /usr/local/etc/php/conf.d/ext-xdebug.ini && \
    echo 'xdebug.show_mem_delta=1' >> /usr/local/etc/php/conf.d/ext-xdebug.ini
    {% else %}
    echo 'xdebug.discover_client_host=true' >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo 'xdebug.client_port=9000' >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo 'xdebug.log=/tmp/xdebug.log' >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo 'xdebug.output_dir="/tmp/xdebug"' >> /usr/local/etc/php/conf.d/xdebug.ini
    {% endif %}
{% endif %}

{% if phpVersionNumeric >= 71 and xdebug == false %}
RUN cd /opt/ && \
    wget https://github.com/shyim/php-dump-client-prefixed/archive/main.zip && \
    unzip main.zip && \
    rm main.zip && \
    mv php-dump-client-prefixed-main php-dump-client-prefixed && \
    echo "auto_prepend_file = /opt/php-dump-client-prefixed/prepend.php" > /usr/local/etc/php/conf.d/vardumpserver.ini
{% endif %}

{% block after_install %}{% endblock %}

ENV HOME /home/dev
USER dev

COPY rootfs/ /

RUN COMPOSER_HOME=/home/dev/.composer1 composer-native-1 global require hirak/prestissimo && \
    COMPOSER_HOME=/home/dev/.composer2 composer-native-2 global require repman-io/composer-plugin && \
    echo "alias ll=\"ls -lha\"" >> ~/.bashrc && \
    echo 'eval $(fnm --fnm-dir=/nvm/.fnm env --shell=bash)' >> ~/.bashrc

WORKDIR /var/www/html

ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php
ENTRYPOINT [ "/entrypoint.sh" ]
STOPSIGNAL SIGKILL
